//! Grain Bubble Svelte Export: Export designs to Svelte components.
//!
//! Why: Export designs to Svelte framework components.
//! Architecture: Svelte component generation with styles.
//! GrainStyle: grain_case, u32/u64, bounded allocations, assertions.
//!
//! 2025-12-07-023640-pst: Grain Bubble Agent

const std = @import("std");
const canvas = @import("canvas.zig");
const component = @import("component.zig");

// Bounded: Max Svelte component content length.
pub const MAX_SVELTE_CONTENT_LEN: u32 = 2 * 1024 * 1024; // 2 MB

// Bounded: Max Svelte class name length.
pub const MAX_CLASS_NAME_LEN: u32 = 64;

// Bounded: Max component name length.
pub const MAX_COMPONENT_NAME_LEN: u32 = 64;

// Svelte component: Svelte file structure.
pub const SvelteComponent = struct {
    template_content: [MAX_SVELTE_CONTENT_LEN]u8,
    template_content_len: u32,
    style_content: [MAX_SVELTE_CONTENT_LEN]u8,
    style_content_len: u32,
    next_class_id: u32,
    component_name: [MAX_COMPONENT_NAME_LEN]u8,
    component_name_len: u32,

    pub fn init(name: []const u8) SvelteComponent {
        std.debug.assert(name.len > 0);
        std.debug.assert(name.len <= MAX_COMPONENT_NAME_LEN);
        var comp = SvelteComponent{
            .template_content = undefined,
            .template_content_len = 0,
            .style_content = undefined,
            .style_content_len = 0,
            .next_class_id = 1,
            .component_name = undefined,
            .component_name_len = 0,
        };
        @memset(comp.template_content[0..], 0);
        @memset(comp.style_content[0..], 0);
        @memset(comp.component_name[0..], 0);
        const name_len = @min(name.len, MAX_COMPONENT_NAME_LEN);
        @memcpy(comp.component_name[0..name_len], name[0..name_len]);
        comp.component_name_len = @as(u32, @intCast(name_len));
        std.debug.assert(comp.component_name_len > 0);
        return comp;
    }

    // Write string to template content.
    fn write_template(self: *SvelteComponent, text: []const u8) void {
        std.debug.assert(text.len > 0);
        std.debug.assert(self.template_content_len + text.len <= MAX_SVELTE_CONTENT_LEN);
        @memcpy(
            self.template_content[self.template_content_len..self.template_content_len + text.len],
            text[0..text.len],
        );
        self.template_content_len += @as(u32, @intCast(text.len));
        std.debug.assert(self.template_content_len <= MAX_SVELTE_CONTENT_LEN);
    }

    // Write string to style content.
    fn write_style(self: *SvelteComponent, text: []const u8) void {
        std.debug.assert(text.len > 0);
        std.debug.assert(self.style_content_len + text.len <= MAX_SVELTE_CONTENT_LEN);
        @memcpy(
            self.style_content[self.style_content_len..self.style_content_len + text.len],
            text[0..text.len],
        );
        self.style_content_len += @as(u32, @intCast(text.len));
        std.debug.assert(self.style_content_len <= MAX_SVELTE_CONTENT_LEN);
    }

    // Convert ARGB color to CSS hex color.
    fn color_to_css_hex(color: u32) [7]u8 {
        const r = (color >> 24) & 0xFF;
        const g = (color >> 16) & 0xFF;
        const b = (color >> 8) & 0xFF;
        var hex: [7]u8 = undefined;
        _ = std.fmt.bufPrint(
            hex[0..],
            "#{:02X}{:02X}{:02X}",
            .{ r, g, b },
        ) catch unreachable;
        return hex;
    }

    // Write Svelte script section.
    pub fn write_script_section(self: *SvelteComponent) void {
        std.debug.assert(self.template_content_len == 0);
        std.debug.assert(self.style_content_len == 0);
        const script = "<script>\n  // Generated by Grain Bubble\n</script>\n\n";
        self.write_template(script);
    }

    // Write Svelte style section start.
    fn write_style_start(self: *SvelteComponent) void {
        const style = "<style>\n";
        self.write_style(style);
    }

    // Write Svelte style section end.
    fn write_style_end(self: *SvelteComponent) void {
        const style = "</style>\n";
        self.write_style(style);
    }

    // Write Svelte template section start.
    fn write_template_start(self: *SvelteComponent) void {
        const template = "<div class=\"component\">\n";
        self.write_template(template);
    }

    // Write Svelte template section end.
    fn write_template_end(self: *SvelteComponent) void {
        const template = "</div>\n";
        self.write_template(template);
    }

    // Export shape to Svelte component.
    pub fn export_shape(
        self: *SvelteComponent,
        shape: *const canvas.Shape,
    ) void {
        std.debug.assert(@intFromPtr(shape) != 0);
        var class_name_buf: [MAX_CLASS_NAME_LEN]u8 = undefined;
        const class_name = std.fmt.bufPrint(
            class_name_buf[0..],
            "shape-{}",
            .{self.next_class_id},
        ) catch return;
        self.next_class_id += 1;
        const color_hex = self.color_to_css_hex(shape.color);
        var html_buf: [512]u8 = undefined;
        const html = std.fmt.bufPrint(
            html_buf[0..],
            "    <div class=\"{s}\"></div>\n",
            .{class_name},
        ) catch return;
        self.write_template(html);
        var css_buf: [512]u8 = undefined;
        const css = std.fmt.bufPrint(
            css_buf[0..],
            ".{s} {{\n  position: absolute;\n  left: {d:.1f}px;\n  ",
            .{ class_name, shape.x },
        ) catch return;
        self.write_style(css);
        const css2 = std.fmt.bufPrint(
            css_buf[0..],
            "top: {d:.1f}px;\n  width: {d:.1f}px;\n  height: {d:.1f}px;\n  ",
            .{ shape.y, shape.width, shape.height },
        ) catch return;
        self.write_style(css2);
        const css3 = std.fmt.bufPrint(
            css_buf[0..],
            "background-color: {s};\n",
            .{color_hex},
        ) catch return;
        self.write_style(css3);
        switch (shape.shape_type) {
            .rectangle => {
                const css4 = "  border-radius: 0;\n";
                self.write_style(css4);
            },
            .circle => {
                const css4 = "  border-radius: 50%;\n";
                self.write_style(css4);
            },
            .rounded_rectangle => {
                const css4 = std.fmt.bufPrint(
                    css_buf[0..],
                    "  border-radius: {d:.1f}px;\n",
                    .{shape.corner_radius},
                ) catch return;
                self.write_style(css4);
            },
        }
        if (shape.stroke_width > 0.0) {
            const stroke_hex = self.color_to_css_hex(shape.stroke_color);
            const css5 = std.fmt.bufPrint(
                css_buf[0..],
                "  border: {d:.1f}px solid {s};\n",
                .{ shape.stroke_width, stroke_hex },
            ) catch return;
            self.write_style(css5);
        }
        const css_close = "}\n\n";
        self.write_style(css_close);
    }

    // Export text to Svelte component.
    pub fn export_text(
        self: *SvelteComponent,
        text: *const canvas.Text,
    ) void {
        std.debug.assert(@intFromPtr(text) != 0);
        var class_name_buf: [MAX_CLASS_NAME_LEN]u8 = undefined;
        const class_name = std.fmt.bufPrint(
            class_name_buf[0..],
            "text-{}",
            .{self.next_class_id},
        ) catch return;
        self.next_class_id += 1;
        const color_hex = self.color_to_css_hex(text.color);
        const text_content = text.content[0..text.content_len];
        var html_buf: [512]u8 = undefined;
        const html = std.fmt.bufPrint(
            html_buf[0..],
            "    <div class=\"{s}\">{s}</div>\n",
            .{ class_name, text_content },
        ) catch return;
        self.write_template(html);
        var css_buf: [512]u8 = undefined;
        const css = std.fmt.bufPrint(
            css_buf[0..],
            ".{s} {{\n  position: absolute;\n  left: {d:.1f}px;\n  ",
            .{ class_name, text.x },
        ) catch return;
        self.write_style(css);
        const css2 = std.fmt.bufPrint(
            css_buf[0..],
            "top: {d:.1f}px;\n  font-size: {d}px;\n  color: {s};\n}}\n\n",
            .{ text.y, text.font_size, color_hex },
        ) catch return;
        self.write_style(css2);
    }

    // Export canvas to Svelte component.
    pub fn export_canvas(
        self: *SvelteComponent,
        canvas_state: *const canvas.Canvas,
    ) void {
        std.debug.assert(@intFromPtr(canvas_state) != 0);
        self.write_script_section();
        self.write_template_start();
        var layer_i: u32 = 0;
        while (layer_i < canvas_state.layers_len) : (layer_i += 1) {
            const layer = &canvas_state.layers[layer_i];
            if (!layer.visible) {
                continue;
            }
            var shape_i: u32 = 0;
            while (shape_i < layer.shapes_len) : (shape_i += 1) {
                self.export_shape(&layer.shapes[shape_i]);
            }
            var text_i: u32 = 0;
            while (text_i < layer.texts_len) : (text_i += 1) {
                self.export_text(&layer.texts[text_i]);
            }
        }
        self.write_template_end();
        self.write_style_start();
        const component_css = ".component {\n  position: relative;\n  " ++
            "width: 100%;\n  height: 100%;\n}\n\n";
        self.write_style(component_css);
        self.write_style_end();
        const style_section = self.style_content[0..self.style_content_len];
        if (style_section.len > 0) {
            const available = MAX_SVELTE_CONTENT_LEN - self.template_content_len;
            if (available >= style_section.len) {
                @memcpy(
                    self.template_content[self.template_content_len..self.template_content_len + style_section.len],
                    style_section[0..style_section.len],
                );
                self.template_content_len += @as(u32, @intCast(style_section.len));
            }
        }
        std.debug.assert(self.template_content_len <= MAX_SVELTE_CONTENT_LEN);
    }

    // Export component variant to Svelte.
    pub fn export_component_variant(
        self: *SvelteComponent,
        variant: *const component.ComponentVariant,
    ) void {
        std.debug.assert(@intFromPtr(variant) != 0);
        var shape_i: u32 = 0;
        while (shape_i < variant.shapes_len) : (shape_i += 1) {
            self.export_shape(&variant.shapes[shape_i]);
        }
        var text_i: u32 = 0;
        while (text_i < variant.texts_len) : (text_i += 1) {
            self.export_text(&variant.texts[text_i]);
        }
    }

    // Get complete Svelte component content (script + template + style).
    pub fn get_content(self: *SvelteComponent) []const u8 {
        std.debug.assert(self.template_content_len > 0);
        const total_len = self.template_content_len + self.style_content_len;
        std.debug.assert(total_len <= MAX_SVELTE_CONTENT_LEN);
        if (self.style_content_len > 0) {
            const available = MAX_SVELTE_CONTENT_LEN - self.template_content_len;
            if (available >= self.style_content_len) {
                @memcpy(
                    self.template_content[self.template_content_len..self.template_content_len + self.style_content_len],
                    self.style_content[0..self.style_content_len],
                );
                self.template_content_len += self.style_content_len;
            }
        }
        std.debug.assert(self.template_content_len <= MAX_SVELTE_CONTENT_LEN);
        return self.template_content[0..self.template_content_len];
    }

    // Get component name as slice.
    pub fn get_component_name(self: *const SvelteComponent) []const u8 {
        std.debug.assert(self.component_name_len > 0);
        return self.component_name[0..self.component_name_len];
    }
};

